vim.pack.add({ 'https://github.com/nvim-mini/mini.nvim' })
require("mini.icons").setup()
require("mini.statusline").setup()
require("mini.cursorword").setup()
require("mini.indentscope").setup()
require("mini.tabline").setup()
